[package]
# include = ["src", "LICENSE-APACHE", "LICENSE-MIT", "README.md", "proto"]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.metadata.cyclonedx]
included_dependencies = "all"
